# Generated by Django 3.1.7 on 2021-03-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='active',
            fields=[
                ('arole', models.CharField(max_length=10)),
                ('aid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apswd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='anouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anc_uid', models.CharField(max_length=10)),
                ('anc_name', models.CharField(max_length=50)),
                ('anc_role', models.CharField(max_length=10)),
                ('anc_dsc', models.CharField(max_length=500)),
                ('anc_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('cemail', models.CharField(max_length=70)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('cmsg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('urole', models.CharField(max_length=10)),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=70)),
                ('utime', models.DateTimeField(auto_now_add=True)),
                ('upswd', models.CharField(max_length=20)),
                ('ucpswd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='verify',
            fields=[
                ('vrole', models.CharField(max_length=10)),
                ('vid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=20)),
            ],
        ),
    ]
