# Generated by Django 3.1.7 on 2021-04-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pr_name', models.CharField(blank=True, max_length=200)),
                ('Pr_title', models.TextField(default='no title...', max_length=300)),
                ('Pr_about', models.TextField(default='no description...', max_length=500)),
                ('Pr_img', models.ImageField(default='static/profile_images/avatar.png', upload_to='static/profile_images/')),
                ('pr_interest', models.CharField(blank=True, max_length=300)),
                ('Pr_friends', models.ManyToManyField(blank=True, related_name='friends', to='myapp.user')),
                ('Pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='myapp.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='myapp.profile')),
            ],
        ),
    ]
