# Generated by Django 3.1.7 on 2021-04-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncement',
            name='anc_img',
            field=models.ImageField(default='static/profile_images/avatar.png', upload_to=''),
        ),
    ]
