# Generated by Django 3.1.7 on 2021-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_anouncement_anc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncement',
            name='anc_img',
            field=models.ImageField(default='static/images/admin.jpg', upload_to=''),
        ),
    ]
