# Generated by Django 3.1.7 on 2021-04-08 17:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_profile_pr_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_content', models.TextField()),
                ('P_img', models.ImageField(blank=True, upload_to='static/profile_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('P_created', models.DateTimeField(auto_now_add=True)),
                ('P_name', models.TextField(blank=True)),
                ('P_name_img', models.ImageField(default='static/images/admin.jpg', upload_to='')),
                ('P_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
                ('P_liked', models.ManyToManyField(blank=True, related_name='likes', to='myapp.Profile')),
            ],
        ),
    ]
