# Generated by Django 3.1.7 on 2021-04-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='apswd',
        ),
        migrations.RemoveField(
            model_name='active',
            name='arole',
        ),
    ]
