# Generated by Django 3.1.7 on 2021-04-13 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210413_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='atime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 13, 11, 32, 14, 792681, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
