# Generated by Django 3.1.7 on 2021-04-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_active_atime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anouncement',
            name='anc_name',
        ),
        migrations.RemoveField(
            model_name='anouncement',
            name='anc_role',
        ),
    ]
