# Generated by Django 3.1.7 on 2021-04-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210414_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_body', models.TextField(blank=True, max_length=1000, null=True)),
                ('m_date', models.DateTimeField(auto_now_add=True)),
                ('m_is_read', models.BooleanField(default=False)),
                ('m_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='myapp.user')),
                ('m_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='myapp.user')),
                ('m_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.user')),
            ],
        ),
    ]
