# Generated by Django 3.1.7 on 2021-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Pr_img',
            field=models.ImageField(default='C:/Users/Dell/projects/bvunite/website/static/profile_images/avatar.png', upload_to='static/profile_images/'),
        ),
    ]
