# Generated by Django 3.1.7 on 2021-04-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
