# Generated by Django 3.1.7 on 2021-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Pr_img',
            field=models.ImageField(default='static/profile_images/avatar.png', upload_to='static/profile_images/'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
